name: 'Echo Message'
on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo input message
        run: echo "${{ inputs.message }}"